### ISSUE TITLE
Expand handleMarkClick to handle a customizable popover/modal/dialog

### ISSUE THREAD

**Issue by malthart** [richard-unterberg/leaflet-nextjs-ts-starter#16]

**Comment by richard-unterberg** [comment]
as said @malthart I have the template code already in a other project but with zustand as global state manager. As far as I can see I created this project without it, to keep it as flexible as possible. Means we need a additional state layer between the popups, since they need a "signal" on which condition they will show/hide. I'll implement a new context for this.

**Comment by richard-unterberg** [comment]
@malthart I added marker popups to the code. Context was not required. but the somewhat bigger 0.1.2 update also features breaking changes in the way how import aliases in typescript are defined - for more information, see -> https://github.com/richard-unterberg/leaflet-nextjs-ts-starter/releases/tag/0.1.2
